BLOCK_SIZE = 70
PLAYER_SIZE = 48
PLAYER_SPEED = 2
PLAYER_LIVES = 6

CAMERA_WIDTH = 1260
CAMERA_HEIGHT = 700

FPS = 60
ANIMATION_FRAMES = 5

GAME_TIME = 60

COLLISION_FACTOR = .8
INVULNERBILITY_FRAMES = 120

ROOT_PATH = './Assets'
SOUND_PATH = 'Sounds'
ANIMATION_PATH = 'Animations'